# Generated by Django 2.2.3 on 2020-09-22 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='congreso',
            old_name='t_congreo',
            new_name='t_congreso',
        ),
        migrations.RemoveField(
            model_name='congreso',
            name='deleted',
        ),
    ]
