# Generated by Django 2.2.3 on 2020-09-23 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0002_auto_20200922_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relcongresocategoriapago',
            old_name='user',
            new_name='categoria',
        ),
        migrations.AlterField(
            model_name='congreso',
            name='t_congreso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MedCongressApp.TipoCongreso'),
        ),
        migrations.AlterField(
            model_name='congreso',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
