# Generated by Django 2.2.3 on 2020-10-06 13:52

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0002_auto_20201006_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='detalle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagencongreso',
            name='imagen',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='MedCongressApp/static/'), upload_to='congreso', verbose_name='imagen'),
        ),
    ]
