# Generated by Django 2.2.3 on 2020-10-06 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0003_auto_20201006_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPonente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('path', models.CharField(help_text='campo para identificarlo por la URL', max_length=50)),
                ('detalle', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'categoria de ponente',
                'verbose_name_plural': 'categorias de los ponentes',
            },
        ),
        migrations.AlterField(
            model_name='ponente',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='MedCongressApp.PerfilUsuario'),
        ),
        migrations.AddField(
            model_name='ponente',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MedCongressApp.CategoriaPonente'),
        ),
    ]
