# Generated by Django 2.2.3 on 2020-09-23 13:39

from django.conf import settings
from django.apps import apps as global_apps
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MedCongressApp', '0003_auto_20200922_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ponencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('duracion', models.CharField(max_length=250)),
                ('fecha_inicio', models.DateTimeField()),
                ('lugar', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('published', models.BooleanField()),
            ],
            options={
                'verbose_name': 'ponencia',
                'verbose_name_plural': 'ponencias',
            },
        ),
        migrations.CreateModel(
            name='Ponente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='congreso',
            name='especialidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MedCongressApp.EspecialidadCongreso'),
        ),
        migrations.CreateModel(
            name='RelPonenciaVotacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votacion', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ponencia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MedCongressApp.Ponencia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RelPonenciaPonente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ponencia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MedCongressApp.Ponencia')),
                ('ponente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MedCongressApp.Ponente')),
            ],
        ),
        migrations.AddField(
            model_name='ponencia',
            name='congreso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MedCongressApp.Congreso'),
        ),
        migrations.AddField(
            model_name='ponencia',
            name='ponente',
            field=models.ManyToManyField(through='MedCongressApp.RelPonenciaPonente', to='MedCongressApp.Ponente'),
        ),
        migrations.AddField(
            model_name='ponencia',
            name='votacion',
            field=models.ManyToManyField(through='MedCongressApp.RelPonenciaVotacion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunSQL(sql='''INSERT INTO  public."MedCongressApp_genero" ( denominacion ) VALUES ('Femenino'
)'''),
#         migrations.RunSQL(sql='''INSERT INTO  public."MedCongressApp_genero" ( denominacion ) VALUES ('Masculino'
# )'''),
    ]
