# Generated by Django 2.2.3 on 2020-09-23 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MedCongressApp', '0004_auto_20200923_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelTallerPonente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ponente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MedCongressApp.Ponente')),
            ],
        ),
        migrations.CreateModel(
            name='RelTallerVotacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votacion', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('duracion', models.CharField(max_length=250)),
                ('precio', models.IntegerField()),
                ('fecha_inicio', models.DateTimeField()),
                ('lugar', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('published', models.BooleanField()),
                ('congreso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MedCongressApp.Congreso')),
                ('ponente', models.ManyToManyField(through='MedCongressApp.RelTallerPonente', to='MedCongressApp.Ponente')),
                ('votacion', models.ManyToManyField(through='MedCongressApp.RelTallerVotacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'taller',
                'verbose_name_plural': 'talleres',
            },
        ),
        migrations.AddField(
            model_name='reltallervotacion',
            name='taller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MedCongressApp.Taller'),
        ),
        migrations.AddField(
            model_name='reltallervotacion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reltallerponente',
            name='taller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MedCongressApp.Taller'),
        ),
    


    ]
