# Generated by Django 2.2.3 on 2020-09-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0005_auto_20200923_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriausuario',
            name='descripcion',
            field=models.CharField(max_length=250, null=True,blank=True),
        ),
    migrations.RunSQL(sql='''INSERT INTO  public."MedCongressApp_genero" ( denominacion ) VALUES ('Femenino')'''),
    migrations.RunSQL(sql='''INSERT INTO  public."MedCongressApp_genero" ( denominacion ) VALUES ('Masculino')'''),
    migrations.RunSQL(sql='''INSERT INTO  public."MedCongressApp_categoriausuario" ( nombre,descripcion ) VALUES ('Médico','descripcion')'''),
    migrations.RunSQL(sql='''INSERT INTO  public."MedCongressApp_categoriausuario" ( nombre,descripcion ) VALUES ('Residente','descripcion')'''),
    migrations.RunSQL(sql='''INSERT INTO  public."MedCongressApp_categoriausuario" ( nombre,descripcion ) VALUES ('Estudiante','descripcion')'''),
    migrations.RunSQL(sql='''INSERT INTO  public."MedCongressApp_categoriausuario" ( nombre,descripcion ) VALUES ('Paramédico','descripcion')'''),
    migrations.RunSQL(sql='''INSERT INTO  public."MedCongressApp_categoriausuario" ( nombre,descripcion ) VALUES ('Laboratorio','descripcion')'''),
    ]
