# Generated by Django 2.2.3 on 2020-09-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0006_auto_20200923_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriausuario',
            name='descripcion',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
