# Generated by Django 2.2.3 on 2020-10-07 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0007_relcongresouser_is_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reltalleruser',
            name='is_pagado',
            field=models.BooleanField(default=True),
        ),
    ]
