# Generated by Django 2.2.3 on 2020-09-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0007_auto_20200923_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriapagocongreso',
            options={'verbose_name': 'categoria de pago del congreso', 'verbose_name_plural': 'categorias de pago para los congresos'},
        ),
        migrations.AlterModelOptions(
            name='ponente',
            options={'verbose_name': 'ponente', 'verbose_name_plural': 'ponentes'},
        ),
        migrations.AddField(
            model_name='congreso',
            name='fecha_inicio',
            field=models.DateTimeField(null=True),
        ),
    ]
