# Generated by Django 2.2.3 on 2020-10-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0008_reltalleruser_is_pagado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='id_openpay',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
