# Generated by Django 2.2.3 on 2020-09-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0008_auto_20200923_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congreso',
            name='detalle',
            field=models.TextField(),
        ),
    ]
