# Generated by Django 2.2.3 on 2020-09-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0009_auto_20200923_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avalcongreso',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='categoriapagocongreso',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='categoriausuario',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='especialidadcongreso',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='tipocongreso',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='avalcongreso',
            name='detalle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoriapagocongreso',
            name='detalle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoriausuario',
            name='detalle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='especialidadcongreso',
            name='detalle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ponencia',
            name='detalle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tipocongreso',
            name='detalle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='congreso',
            name='detalle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
