# Generated by Django 2.2.3 on 2020-09-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0010_auto_20200923_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponencia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
