# Generated by Django 2.2.3 on 2020-10-10 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0011_auto_20201009_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='is_ponente',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
