# Generated by Django 2.2.3 on 2020-09-24 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0011_ponencia_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='relcongresouser',
            name='categoria_pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MedCongressApp.CategoriaPagoCongreso'),
        ),
    ]
