# Generated by Django 2.2.3 on 2020-10-14 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0012_auto_20201009_2211'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='congreso',
            name='lugar',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='cel_profecional',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='is_ponente',
            field=models.BooleanField(blank=True, null=True),
        ),
         
    ]
