# Generated by Django 2.2.3 on 2020-09-24 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0012_relcongresouser_categoria_pago'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relcongresocategoriapago',
            options={'verbose_name': 'Relación Congreso - Categoría de Pago', 'verbose_name_plural': 'Relaciones Congreso - Categoría de Pago'},
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='puntuacion',
        ),
    ]
