# Generated by Django 2.2.3 on 2020-10-12 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0012_auto_20201009_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=250)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
            ],
            options={
                'verbose_name': 'ubicacion',
                'verbose_name_plural': 'ubicaciones',
            },
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='pais',
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='is_ponente',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='ubicacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MedCongressApp.Ubicacion'),
        ),
    ]
