# Generated by Django 2.2.3 on 2020-10-13 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0013_auto_20201012_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriausuario',
            name='published',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='cel_profecional',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
