# Generated by Django 2.2.3 on 2020-10-14 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0013_auto_20201014_1549'),
    ]

   
