# Generated by Django 2.2.3 on 2020-10-14 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0014_auto_20201013_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congreso',
            name='lugar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MedCongressApp.Ubicacion'),
        ),
    ]
