# Generated by Django 2.2.3 on 2020-10-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0015_auto_20201013_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='congreso',
            name='sub_titulo',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
