# Generated by Django 2.2.3 on 2020-10-15 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0015_congreso_sub_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='ubicacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MedCongressApp.Ubicacion'),
        ),
    ]
