# Generated by Django 2.2.3 on 2020-10-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0016_congreso_sub_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congreso',
            name='lugar',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
