# Generated by Django 2.2.3 on 2020-10-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0017_auto_20201014_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congreso',
            name='fecha_inicio',
            field=models.DateTimeField(null=True),
        ),
    ]
