# Generated by Django 2.2.3 on 2020-10-15 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0017_auto_20201014_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagencongreso',
            name='congreso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MedCongressApp.Congreso'),
        ),
    ]
