# Generated by Django 2.2.3 on 2020-10-16 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0019_auto_20201015_2021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reltalleruser',
            options={'verbose_name': 'Relación Taller - usuario', 'verbose_name_plural': 'Relaciones Talleres - usuarios'},
        ),
        migrations.AlterUniqueTogether(
            name='reltalleruser',
            unique_together=set(),
        ),
    ]
