# Generated by Django 2.2.3 on 2020-10-17 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0020_auto_20201015_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taller',
            name='precio',
        ),
    ]
