# Generated by Django 2.2.3 on 2020-10-18 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0021_remove_taller_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponencia',
            name='lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MedCongressApp.Ubicacion'),
        ),
        migrations.AlterField(
            model_name='taller',
            name='lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MedCongressApp.Ubicacion'),
        ),
    ]
