# Generated by Django 2.2.3 on 2020-10-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0022_auto_20201018_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponencia',
            name='cod_video',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
