# Generated by Django 2.2.3 on 2020-10-22 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0026_auto_20201022_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagencongreso',
            name='congreso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MedCongressApp.Congreso'),
        ),
    ]
