# Generated by Django 2.2.3 on 2020-10-23 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0027_auto_20201022_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='detalle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='relponenciaponente',
            name='ponencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedCongressApp.Ponencia'),
        ),
        migrations.AlterField(
            model_name='relponenciaponente',
            name='ponente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedCongressApp.Ponente'),
        ),
    ]
