# Generated by Django 2.2.3 on 2020-10-24 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0028_auto_20201023_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='activation_key',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='taller',
            name='ponente',
            field=models.ManyToManyField(related_name='taller_ponente', through='MedCongressApp.RelTallerPonente', to='MedCongressApp.Ponente'),
        ),
    ]
