# Generated by Django 2.2.3 on 2020-10-25 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0029_auto_20201023_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('duracion', models.CharField(max_length=250)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('path', models.CharField(help_text='campo para identificarlo por la URL', max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('published', models.BooleanField()),
                ('congreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedCongressApp.Congreso')),
            ],
            options={
                'verbose_name': 'bloque',
                'verbose_name_plural': 'bloques',
            },
        ),
        migrations.CreateModel(
            name='Modelador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='MedCongressApp.PerfilUsuario')),
            ],
            options={
                'verbose_name': 'modelador',
                'verbose_name_plural': 'modeladores',
            },
        ),
        migrations.RemoveField(
            model_name='relponenciaponente',
            name='categoria',
        ),
        migrations.AddField(
            model_name='ponencia',
            name='bloque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MedCongressApp.Bloque'),
        ),
        migrations.AddField(
            model_name='taller',
            name='bloque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MedCongressApp.Bloque'),
        ),
        migrations.CreateModel(
            name='RelBloqueModelador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedCongressApp.Bloque')),
                ('modelador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedCongressApp.Modelador')),
            ],
            options={
                'verbose_name': 'Relación Madelador - Bloque',
                'verbose_name_plural': 'Relaciones modelador - bloque',
                'unique_together': {('modelador', 'bloque')},
            },
        ),
    ]
