# Generated by Django 2.2.3 on 2020-10-25 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0030_auto_20201024_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloque',
            name='modelador',
            field=models.ManyToManyField(related_name='bloque_modelador', through='MedCongressApp.RelBloqueModelador', to='MedCongressApp.Modelador'),
        ),
    ]
