# Generated by Django 2.2.3 on 2020-10-27 01:33

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0030_auto_20201025_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosiniciales',
            name='aviso_privacidad',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='MedCongressApp/static/'), upload_to='usuarios'),
        ),
        migrations.AlterField(
            model_name='ponencia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='MedCongressApp/static/'), upload_to='ponencias'),
        ),
        migrations.AlterField(
            model_name='reltallerponente',
            name='ponente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedCongressApp.Ponente'),
        ),
        migrations.AlterField(
            model_name='reltallerponente',
            name='taller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedCongressApp.Taller'),
        ),
    ]
