# Generated by Django 2.2.3 on 2020-11-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0034_auto_20201106_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='congreso',
            name='datos_interes',
            field=models.TextField(null=True),
        ),
    ]
