# Generated by Django 2.2.3 on 2020-11-10 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0037_cuestionariopregunta'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuestionarioRespuestas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(max_length=250)),
                ('is_correcto', models.BooleanField()),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedCongressApp.CuestionarioPregunta')),
            ],
        ),
    ]
