# Generated by Django 2.2.3 on 2020-11-10 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0038_cuestionariorespuestas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuestionariopregunta',
            options={'verbose_name': 'Pregunta del Cuestionario', 'verbose_name_plural': 'Preguntas del Cuestionario'},
        ),
        migrations.AddField(
            model_name='cuestionariopregunta',
            name='published',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='cuestionariorespuestas',
            name='published',
            field=models.BooleanField(null=True),
        ),
    ]
