# Generated by Django 2.2.3 on 2020-11-11 01:48

import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0039_auto_20201110_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='banderas',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='MedCongressApp/static/'), upload_to='banderas'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='denominacion',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Záéíóúñ\\s]+$', 'Entre un nombre válido. Ej(México)')]),
        ),
    ]
