# Generated by Django 2.2.3 on 2020-11-12 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0040_auto_20201110_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='facebook',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='linkedin',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='twitter',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='youtube',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
