# Generated by Django 2.2.3 on 2020-11-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0044_auto_20201116_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='congreso',
            name='meta_title',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='meta_description',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='meta_keywords',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='meta_og_description',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='meta_og_imagen',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='meta_og_title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='meta_og_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='meta_og_url',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='meta_title',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='meta_twitter_card',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='meta_twitter_creator',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='meta_twitter_site',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ponencia',
            name='meta_title',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='taller',
            name='meta_title',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
