# Generated by Django 2.2.3 on 2020-11-17 17:31

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0046_metapaginicio_metapaglistcongreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metapaginicio',
            name='meta_og_imagen',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='MedCongressApp/static/'), upload_to='metas'),
        ),
        migrations.AlterField(
            model_name='metapaglistcongreso',
            name='meta_og_imagen',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='MedCongressApp/static/'), upload_to='metas'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='meta_og_imagen',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='MedCongressApp/static/'), upload_to='metas'),
        ),
        migrations.AlterField(
            model_name='ponencia',
            name='meta_og_imagen',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='MedCongressApp/static/'), upload_to='metas'),
        ),
        migrations.AlterField(
            model_name='taller',
            name='meta_og_imagen',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='MedCongressApp/static/'), upload_to='metas'),
        ),
    ]
