# Generated by Django 2.2.3 on 2020-11-19 02:42

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0047_auto_20201117_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='congreso',
            name='aprobado',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='congreso',
            name='cant_preguntas',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='congreso',
            name='foto_constancia',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location='MedCongressApp/static/'), upload_to='congreso/img_constancia'),
        ),
        migrations.AddField(
            model_name='relcongresouser',
            name='is_constancia',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='congreso',
            name='meta_description',
            field=models.TextField(max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='congreso',
            name='meta_keywords',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='congreso',
            name='meta_og_description',
            field=models.TextField(max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='metapaginicio',
            name='meta_description',
            field=models.TextField(max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='metapaginicio',
            name='meta_keywords',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='metapaginicio',
            name='meta_og_description',
            field=models.TextField(max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='meta_description',
            field=models.TextField(max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='meta_keywords',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='meta_og_description',
            field=models.TextField(max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='puesto',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ponencia',
            name='meta_description',
            field=models.TextField(max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='ponencia',
            name='meta_keywords',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ponencia',
            name='meta_og_description',
            field=models.TextField(max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='taller',
            name='meta_description',
            field=models.TextField(max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='taller',
            name='meta_keywords',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='taller',
            name='meta_og_description',
            field=models.TextField(max_length=160, null=True),
        ),
    ]
