# Generated by Django 2.2.3 on 2020-11-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0048_auto_20201118_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='relcongresouser',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
