# Generated by Django 2.2.3 on 2020-11-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0050_auto_20201119_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='relcongresouser',
            name='cuestionario',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
