# Generated by Django 2.2.3 on 2020-11-22 18:54

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0051_relcongresouser_cuestionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='relcongresouser',
            name='foto_constancia',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location='MedCongressApp/static/'), upload_to='congreso/img_constancia'),
        ),
    ]
