# Generated by Django 2.2.3 on 2020-11-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0052_relcongresouser_foto_constancia'),
    ]

    operations = [
        migrations.AddField(
            model_name='relcongresouser',
            name='uuid_factura',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
