# Generated by Django 2.2.3 on 2020-11-25 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0054_reltalleruser_uuid_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponencia',
            name='is_info',
            field=models.BooleanField(null=True),
        ),
    ]
