# Generated by Django 2.2.3 on 2020-11-26 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0055_ponencia_is_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='congreso',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='PreguntasFrecuentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=250)),
                ('respuesta', models.TextField()),
                ('congreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedCongressApp.Congreso')),
            ],
            options={
                'verbose_name': 'Pregunta frecuente de un Congreso',
                'verbose_name_plural': 'Preguntas fercuentes de los Congresos',
            },
        ),
    ]
