# Generated by Django 2.2.3 on 2020-11-26 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0056_auto_20201126_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntasfrecuentes',
            name='published',
            field=models.BooleanField(null=True),
        ),
    ]
