# Generated by Django 2.2.3 on 2020-11-28 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0057_preguntasfrecuentes_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='congreso',
            name='streaming',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
