# Generated by Django 2.2.3 on 2020-11-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0058_congreso_streaming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congreso',
            name='streaming',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ponencia',
            name='cod_video',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
