# Generated by Django 2.2.3 on 2020-11-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0059_auto_20201128_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congreso',
            name='streaming',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ponencia',
            name='cod_video',
            field=models.TextField(null=True),
        ),
    ]
