# Generated by Django 2.2.3 on 2020-11-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0060_auto_20201128_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponencia',
            name='cod_video',
            field=models.TextField(blank=True, null=True),
        ),
    ]
