# Generated by Django 2.2.3 on 2020-11-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0061_auto_20201128_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congreso',
            name='streaming',
            field=models.TextField(blank=True, null=True),
        ),
    ]
