# Generated by Django 2.2.3 on 2020-12-01 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0062_auto_20201128_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MedCongressApp.CategoriaUsuario'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='genero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MedCongressApp.Genero'),
        ),
    ]
