# Generated by Django 2.2.3 on 2020-12-02 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0063_auto_20201201_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='num_telefono',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
