# Generated by Django 2.2.3 on 2020-12-16 03:47

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0064_auto_20201201_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelCongresoSocio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'relacion congreso - socio',
                'verbose_name_plural': 'relaciones congreso - socios',
            },
        ),
        migrations.CreateModel(
            name='SocioCongreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='MedCongressApp/static/'), upload_to='socios')),
                ('url', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'socio del congreso',
                'verbose_name_plural': 'socios de los congresos',
            },
        ),
        migrations.DeleteModel(
            name='CategoriaPonente',
        ),
        migrations.AlterField(
            model_name='avalcongreso',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='categoriapagocongreso',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='congreso',
            name='path',
            field=models.CharField(help_text='campo para identificarlo por la URL', max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='congreso',
            name='titulo',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='especialidadcongreso',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='especialidades',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='genero',
            name='denominacion',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='tipocongreso',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='relcongresosocio',
            name='congreso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedCongressApp.Congreso'),
        ),
        migrations.AddField(
            model_name='relcongresosocio',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedCongressApp.SocioCongreso'),
        ),
        migrations.AlterUniqueTogether(
            name='relcongresosocio',
            unique_together={('socio', 'congreso')},
        ),
    ]
