# Generated by Django 2.2.3 on 2020-12-17 14:28

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0065_auto_20201215_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ofrecemos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('icono', models.CharField(max_length=250)),
                ('texto', models.TextField()),
            ],
            options={
                'verbose_name': 'ofrecemos',
                'verbose_name_plural': 'ofrecemos',
            },
        ),
        migrations.CreateModel(
            name='QuienesSomos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('sub_titulo', models.CharField(max_length=250)),
                ('texto', models.TextField()),
            ],
            options={
                'verbose_name': 'quienes somos',
                'verbose_name_plural': 'quienes somos',
            },
        ),
        migrations.CreateModel(
            name='ImagenQuienesSomos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='MedCongressApp/static/'), upload_to='congreso', verbose_name='imagen')),
                ('q_somos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MedCongressApp.QuienesSomos')),
            ],
            options={
                'verbose_name': 'imagen de quienes somos',
                'verbose_name_plural': 'Imagenes de quienes somos',
            },
        ),
    ]
