# Generated by Django 2.2.3 on 2020-12-17 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0066_imagenquienessomos_ofrecemos_quienessomos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenquienessomos',
            name='q_somos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedCongressApp.QuienesSomos'),
        ),
    ]
