# Generated by Django 2.2.3 on 2020-12-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0067_auto_20201217_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Contacto footer',
                'verbose_name_plural': 'Contacto footer',
            },
        ),
    ]
