# Generated by Django 2.2.3 on 2020-12-18 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0068_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='cod_video',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metapaginicio',
            name='meta_description',
            field=models.TextField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='metapaginicio',
            name='meta_keywords',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='metapaginicio',
            name='meta_og_description',
            field=models.TextField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='metapaginicio',
            name='meta_og_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='metapaginicio',
            name='meta_og_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='metapaginicio',
            name='meta_og_url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='metapaginicio',
            name='meta_title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='metapaginicio',
            name='meta_twitter_card',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='metapaginicio',
            name='meta_twitter_creator',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='metapaginicio',
            name='meta_twitter_site',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
