# Generated by Django 2.2.3 on 2021-01-12 18:48

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0071_auto_20201222_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='congreso',
            name='programa',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='MedCongressApp/static/'), upload_to='programas'),
        ),
    ]
