# Generated by Django 2.2.3 on 2021-01-12 19:17

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0072_congreso_programa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congreso',
            name='programa',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='MedCongressApp/static/'), upload_to='programas'),
        ),
    ]
