# Generated by Django 2.2.3 on 2021-01-13 04:19

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0073_auto_20210112_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='congreso',
            name='detalles_tipo_boleto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagencongreso',
            name='imagen',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='MedCongressApp/static/'), upload_to='congreso'),
        ),
    ]
