# Generated by Django 2.2.3 on 2021-01-13 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0074_auto_20210112_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='detalles_tipo_boleto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
