# Generated by Django 2.2.3 on 2021-01-14 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0077_congreso_ver_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relponenciavotacion',
            name='ponencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedCongressApp.Ponencia'),
        ),
        migrations.AlterField(
            model_name='relponenciavotacion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
