# Generated by Django 2.2.3 on 2021-01-19 15:56

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0078_auto_20210114_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='foto_constancia',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location='MedCongressApp/static/'), upload_to='congreso/img_constancia'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='denominacion',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
