# Generated by Django 2.2.3 on 2021-01-19 16:26

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0079_auto_20210119_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='reltalleruser',
            name='fecha_constancia',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='reltalleruser',
            name='foto_constancia',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location='MedCongressApp/static/'), upload_to='congreso/img_constancia'),
        ),
        migrations.AddField(
            model_name='reltalleruser',
            name='is_constancia',
            field=models.BooleanField(null=True),
        ),
    ]
