# Generated by Django 2.2.3 on 2021-01-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0080_auto_20210119_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
