# Generated by Django 2.2.3 on 2021-01-21 20:00

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0081_taller_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='MedCongressApp/static/'), upload_to='congreso', verbose_name='imagen')),
            ],
            options={
                'verbose_name': 'Imagen Home',
            },
        ),
    ]
