# Generated by Django 2.2.3 on 2021-02-10 21:47

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0085_auto_20210203_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('abreviatura', models.CharField(max_length=4, unique=True)),
            ],
            options={
                'verbose_name': 'idioma',
                'verbose_name_plural': 'idiomas',
            },
        ),
        migrations.RemoveField(
            model_name='congreso',
            name='programa',
        ),
        migrations.CreateModel(
            name='DocumentoPrograma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='MedCongressApp/static/'), upload_to='programas')),
                ('texto', models.CharField(max_length=25)),
                ('congreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedCongressApp.Congreso')),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedCongressApp.Idioma')),
            ],
            options={
                'verbose_name': 'DocumentoPrograma',
            },
        ),
    ]
