# Generated by Django 2.2.3 on 2021-02-18 03:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0086_auto_20210210_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avalcongreso',
            name='nombre',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>Nombre</b> debe tener máximo 50 caracteres'}, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='bloque',
            name='duracion',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>Duración </b> debe tener máximo 250 caracteres'}, max_length=250),
        ),
        migrations.AlterField(
            model_name='bloque',
            name='titulo',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>Título </b> debe tener máximo 250 caracteres'}, max_length=250),
        ),
        migrations.AlterField(
            model_name='categoriapagocongreso',
            name='nombre',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>Nombre</b> debe tener máximo 50 caracteres'}, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='categoriausuario',
            name='nombre',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>Nombre</b> debe tener máximo 50 caracteres'}, max_length=50),
        ),
        migrations.AlterField(
            model_name='congreso',
            name='meta_description',
            field=models.TextField(blank=True, error_messages={'max_length': 'El Campo <b>Metas Principales Descripción</b> debe tener máximo 160 caracteres'}, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='congreso',
            name='meta_keywords',
            field=models.TextField(blank=True, error_messages={'max_length': 'El Campo <b>Metas Principales Palabras Claves </b> debe tener máximo 250 caracteres'}, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='congreso',
            name='meta_og_description',
            field=models.TextField(blank=True, error_messages={'max_length': 'El Campo <b>Metas para FaceBook Descripción</b> debe tener máximo 160 caracteres'}, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='congreso',
            name='meta_og_title',
            field=models.CharField(blank=True, error_messages={'max_length': 'El Campo <b>Metas para FaceBook Título</b> debe tener máximo 50 caracteres'}, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='congreso',
            name='meta_og_type',
            field=models.CharField(blank=True, error_messages={'max_length': 'El Campo <b>Metas para FaceBook Tipo</b> debe tener máximo 50 caracteres'}, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='congreso',
            name='meta_og_url',
            field=models.CharField(blank=True, error_messages={'max_length': 'El Campo <b>Metas para FaceBook URL</b> debe tener máximo 250 caracteres'}, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='congreso',
            name='meta_title',
            field=models.CharField(blank=True, error_messages={'max_length': 'El Campo <b>Metas Principales Título </b> debe tener máximo 50 caracteres'}, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='congreso',
            name='meta_twitter_card',
            field=models.CharField(blank=True, error_messages={'max_length': 'El Campo <b>Metas para Redes Sociales Card</b> debe tener máximo 50 caracteres'}, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='congreso',
            name='meta_twitter_creator',
            field=models.CharField(blank=True, error_messages={'max_length': 'El Campo <b>Metas para Redes Sociales Creador</b> debe tener máximo 50 caracteres'}, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='congreso',
            name='meta_twitter_site',
            field=models.CharField(blank=True, error_messages={'max_length': 'El Campo <b>Metas para Redes Sociales Sitio</b> debe tener máximo 250 caracteres'}, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='congreso',
            name='sub_titulo',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>SubTítulo</b> debe tener máximo 250 caracteres'}, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='congreso',
            name='titulo',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>Título</b> debe tener máximo 250 caracteres'}, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='cuestionariopregunta',
            name='pregunta',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>Pregunta </b> debe tener máximo 250 caracteres'}, max_length=250),
        ),
        migrations.AlterField(
            model_name='cuestionariorespuestas',
            name='respuesta',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>Respuesta </b> debe tener máximo 250 caracteres'}, max_length=250),
        ),
        migrations.AlterField(
            model_name='documento',
            name='titulo',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>Título </b> debe tener máximo 25 caracteres'}, max_length=25),
        ),
        migrations.AlterField(
            model_name='documentoprograma',
            name='texto',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>Texto </b> debe tener máximo 25 caracteres'}, max_length=25),
        ),
        migrations.AlterField(
            model_name='especialidadcongreso',
            name='nombre',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>Nombre</b> debe tener máximo 50 caracteres'}, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='especialidades',
            name='nombre',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>Nombre</b> debe tener máximo 50 caracteres'}, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='direccion',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>Dirección </b> debe tener máximo 250 caracteres'}, max_length=250),
        ),
        migrations.AlterField(
            model_name='footer',
            name='telefono',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>Teléfono </b> debe tener máximo 20 caracteres'}, max_length=20, validators=[django.core.validators.RegexValidator(message='Entre un No. de <b>Teléfono</b> correcto. Ej. <b>(+99)999-999-999</b>', regex='^[0-9()+-]+$')]),
        ),
        migrations.AlterField(
            model_name='footer',
            name='whatsapp',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>Whatsapp </b> debe tener máximo 20 caracteres'}, max_length=20, validators=[django.core.validators.RegexValidator(message='Entre un No. de <b>Whatsapp</b> correcto. Ej. <b>(+99)999-999-999</b>', regex='^[0-9()+-]+$')]),
        ),
        migrations.AlterField(
            model_name='genero',
            name='denominacion',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>Denominación</b> debe tener máximo 20 caracteres'}, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='abreviatura',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>Abreviatura </b> debe tener máximo 4 caracteres'}, max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='nombre',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>Nombre </b> debe tener máximo 20 caracteres'}, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='metapaginicio',
            name='meta_description',
            field=models.TextField(blank=True, error_messages={'max_length': 'El Campo <b>Metas Principales Descripción</b> debe tener máximo 160 caracteres'}, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='metapaginicio',
            name='meta_keywords',
            field=models.TextField(blank=True, error_messages={'max_length': 'El Campo <b>Metas Principales Palabras Claves </b> debe tener máximo 250 caracteres'}, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='metapaginicio',
            name='meta_og_description',
            field=models.TextField(blank=True, error_messages={'max_length': 'El Campo <b>Metas para FaceBook Descripción</b> debe tener máximo 160 caracteres'}, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='metapaginicio',
            name='meta_og_title',
            field=models.CharField(blank=True, error_messages={'max_length': 'El Campo <b>Metas para FaceBook Título</b> debe tener máximo 50 caracteres'}, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='metapaginicio',
            name='meta_og_type',
            field=models.CharField(blank=True, error_messages={'max_length': 'El Campo <b>Metas para FaceBook Tipo</b> debe tener máximo 50 caracteres'}, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='metapaginicio',
            name='meta_og_url',
            field=models.CharField(blank=True, error_messages={'max_length': 'El Campo <b>Metas para FaceBook URL</b> debe tener máximo 250 caracteres'}, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='metapaginicio',
            name='meta_title',
            field=models.CharField(blank=True, error_messages={'max_length': 'El Campo <b>Metas Principales Título </b> debe tener máximo 50 caracteres'}, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='metapaginicio',
            name='meta_twitter_card',
            field=models.CharField(blank=True, error_messages={'max_length': 'El Campo <b>Metas para Redes Sociales Card</b> debe tener máximo 50 caracteres'}, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='metapaginicio',
            name='meta_twitter_creator',
            field=models.CharField(blank=True, error_messages={'max_length': 'El Campo <b>Metas para Redes Sociales Creador</b> debe tener máximo 50 caracteres'}, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='metapaginicio',
            name='meta_twitter_site',
            field=models.CharField(blank=True, error_messages={'max_length': 'El Campo <b>Metas para Redes Sociales Sitio</b> debe tener máximo 250 caracteres'}, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='metapaglistcongreso',
            name='meta_description',
            field=models.TextField(blank=True, error_messages={'max_length': 'El Campo <b>Metas Principales Descripción</b> debe tener máximo 160 caracteres'}, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='metapaglistcongreso',
            name='meta_keywords',
            field=models.TextField(blank=True, error_messages={'max_length': 'El Campo <b>Metas Principales Palabras Claves </b> debe tener máximo 250 caracteres'}, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='metapaglistcongreso',
            name='meta_og_description',
            field=models.TextField(blank=True, error_messages={'max_length': 'El Campo <b>Metas para FaceBook Descripción</b> debe tener máximo 160 caracteres'}, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='metapaglistcongreso',
            name='meta_og_title',
            field=models.CharField(blank=True, error_messages={'max_length': 'El Campo <b>Metas para FaceBook Título</b> debe tener máximo 50 caracteres'}, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='metapaglistcongreso',
            name='meta_og_type',
            field=models.CharField(blank=True, error_messages={'max_length': 'El Campo <b>Metas para FaceBook Tipo</b> debe tener máximo 50 caracteres'}, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='metapaglistcongreso',
            name='meta_og_url',
            field=models.CharField(blank=True, error_messages={'max_length': 'El Campo <b>Metas para FaceBook URL</b> debe tener máximo 250 caracteres'}, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='metapaglistcongreso',
            name='meta_title',
            field=models.CharField(blank=True, error_messages={'max_length': 'El Campo <b>Metas Principales Título </b> debe tener máximo 50 caracteres'}, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='metapaglistcongreso',
            name='meta_twitter_card',
            field=models.CharField(blank=True, error_messages={'max_length': 'El Campo <b>Metas para Redes Sociales Card</b> debe tener máximo 50 caracteres'}, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='metapaglistcongreso',
            name='meta_twitter_creator',
            field=models.CharField(blank=True, error_messages={'max_length': 'El Campo <b>Metas para Redes Sociales Creador</b> debe tener máximo 50 caracteres'}, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='metapaglistcongreso',
            name='meta_twitter_site',
            field=models.CharField(blank=True, error_messages={'max_length': 'El Campo <b>Metas para Redes Sociales Sitio</b> debe tener máximo 250 caracteres'}, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ofrecemos',
            name='icono',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>Icono </b> debe tener máximo 250 caracteres'}, max_length=250),
        ),
        migrations.AlterField(
            model_name='ofrecemos',
            name='titulo',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>Título </b> debe tener máximo 250 caracteres'}, max_length=250),
        ),
        migrations.AlterField(
            model_name='pais',
            name='denominacion',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>Denominación</b> debe tener máximo 50 caracteres'}, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='facebook',
            field=models.CharField(error_messages={'max_length': 'El Campo <b> Facebook</b> debe tener máximo 50 caracteres'}, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='linkedin',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>Linkedin</b> debe tener máximo 50 caracteres'}, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='meta_description',
            field=models.TextField(blank=True, error_messages={'max_length': 'El Campo <b>Metas Principales Descripción</b> debe tener máximo 160 caracteres'}, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='meta_keywords',
            field=models.TextField(blank=True, error_messages={'max_length': 'El Campo <b>Metas Principales Palabras Claves </b> debe tener máximo 250 caracteres'}, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='meta_og_description',
            field=models.TextField(blank=True, error_messages={'max_length': 'El Campo <b>Metas para FaceBook Descripción</b> debe tener máximo 160 caracteres'}, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='meta_og_title',
            field=models.CharField(blank=True, error_messages={'max_length': 'El Campo <b>Metas para FaceBook Título</b> debe tener máximo 50 caracteres'}, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='meta_og_type',
            field=models.CharField(blank=True, error_messages={'max_length': 'El Campo <b>Metas para FaceBook Tipo</b> debe tener máximo 50 caracteres'}, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='meta_og_url',
            field=models.CharField(blank=True, error_messages={'max_length': 'El Campo <b>Metas para FaceBook URL</b> debe tener máximo 250 caracteres'}, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='meta_title',
            field=models.CharField(blank=True, error_messages={'max_length': 'El Campo <b>Metas Principales Título </b> debe tener máximo 50 caracteres'}, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='meta_twitter_card',
            field=models.CharField(blank=True, error_messages={'max_length': 'El Campo <b>Metas para Redes Sociales Card</b> debe tener máximo 50 caracteres'}, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='meta_twitter_creator',
            field=models.CharField(blank=True, error_messages={'max_length': 'El Campo <b>Metas para Redes Sociales Creador</b> debe tener máximo 50 caracteres'}, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='meta_twitter_site',
            field=models.CharField(blank=True, error_messages={'max_length': 'El Campo <b>Metas para Redes Sociales Sitio</b> debe tener máximo 250 caracteres'}, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='twitter',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>Twitter</b> debe tener máximo 50 caracteres'}, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='youtube',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>Youtube</b> debe tener máximo 50 caracteres'}, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ponencia',
            name='duracion',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>Duración </b> debe tener máximo 250 caracteres'}, max_length=250),
        ),
        migrations.AlterField(
            model_name='ponencia',
            name='meta_description',
            field=models.TextField(blank=True, error_messages={'max_length': 'El Campo <b>Metas Principales Descripción</b> debe tener máximo 160 caracteres'}, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='ponencia',
            name='meta_keywords',
            field=models.TextField(blank=True, error_messages={'max_length': 'El Campo <b>Metas Principales Palabras Claves </b> debe tener máximo 250 caracteres'}, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ponencia',
            name='meta_og_description',
            field=models.TextField(blank=True, error_messages={'max_length': 'El Campo <b>Metas para FaceBook Descripción</b> debe tener máximo 160 caracteres'}, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='ponencia',
            name='meta_og_title',
            field=models.CharField(blank=True, error_messages={'max_length': 'El Campo <b>Metas para FaceBook Título</b> debe tener máximo 50 caracteres'}, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ponencia',
            name='meta_og_type',
            field=models.CharField(blank=True, error_messages={'max_length': 'El Campo <b>Metas para FaceBook Tipo</b> debe tener máximo 50 caracteres'}, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ponencia',
            name='meta_og_url',
            field=models.CharField(blank=True, error_messages={'max_length': 'El Campo <b>Metas para FaceBook URL</b> debe tener máximo 250 caracteres'}, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ponencia',
            name='meta_title',
            field=models.CharField(blank=True, error_messages={'max_length': 'El Campo <b>Metas Principales Título </b> debe tener máximo 50 caracteres'}, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ponencia',
            name='meta_twitter_card',
            field=models.CharField(blank=True, error_messages={'max_length': 'El Campo <b>Metas para Redes Sociales Card</b> debe tener máximo 50 caracteres'}, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ponencia',
            name='meta_twitter_creator',
            field=models.CharField(blank=True, error_messages={'max_length': 'El Campo <b>Metas para Redes Sociales Creador</b> debe tener máximo 50 caracteres'}, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ponencia',
            name='meta_twitter_site',
            field=models.CharField(blank=True, error_messages={'max_length': 'El Campo <b>Metas para Redes Sociales Sitio</b> debe tener máximo 250 caracteres'}, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ponencia',
            name='titulo',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>Título </b> debe tener máximo 250 caracteres'}, max_length=250),
        ),
        migrations.AlterField(
            model_name='preguntasfrecuentes',
            name='pregunta',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>Pregunta </b> debe tener máximo 250 caracteres'}, max_length=250),
        ),
        migrations.AlterField(
            model_name='quienessomos',
            name='sub_titulo',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>SubTítulo </b> debe tener máximo 250 caracteres'}, max_length=250),
        ),
        migrations.AlterField(
            model_name='quienessomos',
            name='titulo',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>Título </b> debe tener máximo 250 caracteres'}, max_length=250),
        ),
        migrations.AlterField(
            model_name='sociocongreso',
            name='nombre',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>Nombre</b> debe tener máximo 50 caracteres'}, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='sociocongreso',
            name='url',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>URL</b> debe tener máximo 250 caracteres'}, max_length=250),
        ),
        migrations.AlterField(
            model_name='taller',
            name='duracion',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>Duración </b> debe tener máximo 250 caracteres'}, max_length=250),
        ),
        migrations.AlterField(
            model_name='taller',
            name='meta_description',
            field=models.TextField(blank=True, error_messages={'max_length': 'El Campo <b>Metas Principales Descripción</b> debe tener máximo 160 caracteres'}, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='taller',
            name='meta_keywords',
            field=models.TextField(blank=True, error_messages={'max_length': 'El Campo <b>Metas Principales Palabras Claves </b> debe tener máximo 250 caracteres'}, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='taller',
            name='meta_og_description',
            field=models.TextField(blank=True, error_messages={'max_length': 'El Campo <b>Metas para FaceBook Descripción</b> debe tener máximo 160 caracteres'}, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='taller',
            name='meta_og_title',
            field=models.CharField(blank=True, error_messages={'max_length': 'El Campo <b>Metas para FaceBook Título</b> debe tener máximo 50 caracteres'}, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='taller',
            name='meta_og_type',
            field=models.CharField(blank=True, error_messages={'max_length': 'El Campo <b>Metas para FaceBook Tipo</b> debe tener máximo 50 caracteres'}, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='taller',
            name='meta_og_url',
            field=models.CharField(blank=True, error_messages={'max_length': 'El Campo <b>Metas para FaceBook URL</b> debe tener máximo 250 caracteres'}, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='taller',
            name='meta_title',
            field=models.CharField(blank=True, error_messages={'max_length': 'El Campo <b>Metas Principales Título </b> debe tener máximo 50 caracteres'}, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='taller',
            name='meta_twitter_card',
            field=models.CharField(blank=True, error_messages={'max_length': 'El Campo <b>Metas para Redes Sociales Card</b> debe tener máximo 50 caracteres'}, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='taller',
            name='meta_twitter_creator',
            field=models.CharField(blank=True, error_messages={'max_length': 'El Campo <b>Metas para Redes Sociales Creador</b> debe tener máximo 50 caracteres'}, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='taller',
            name='meta_twitter_site',
            field=models.CharField(blank=True, error_messages={'max_length': 'El Campo <b>Metas para Redes Sociales Sitio</b> debe tener máximo 250 caracteres'}, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='taller',
            name='titulo',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>Título </b> debe tener máximo 250 caracteres'}, max_length=250),
        ),
        migrations.AlterField(
            model_name='tipocongreso',
            name='nombre',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>Nombre</b> debe tener máximo 50 caracteres'}, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='direccion',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>Dirección</b> debe tener máximo 250 caracteres'}, max_length=250),
        ),
    ]
