# Generated by Django 2.2.3 on 2021-02-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0088_congreso_vid_publicidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_congreso_cat_pago', models.IntegerField()),
                ('tipo_evento', models.CharField(max_length=20)),
                ('id_evento', models.IntegerField()),
                ('nombre_congreso', models.CharField(max_length=250)),
                ('id_cat_pago', models.IntegerField()),
                ('nombre_cat_pago', models.CharField(max_length=250)),
                ('precio', models.FloatField()),
                ('pagar', models.FloatField()),
                ('moneda', models.CharField(max_length=3)),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Cart',
            },
        ),
    ]
