# Generated by Django 2.2.3 on 2021-02-23 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0089_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='Carrito',
        ),
    ]
