# Generated by Django 2.2.3 on 2021-02-23 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0090_auto_20210223_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MedCongressApp.PerfilUsuario'),
            preserve_default=False,
        ),
    ]
