# Generated by Django 2.2.3 on 2021-03-03 19:50

import django.core.files.storage
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0096_auto_20210223_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avalcongreso',
            name='url',
            field=models.URLField(error_messages={'max_length': 'El Campo <b>URL</b> debe tener máximo 250 caracteres'}, max_length=250),
        ),
        migrations.AlterField(
            model_name='categoriapagocongreso',
            name='nombre',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>Nombre</b> debe tener máximo 50 caracteres'}, max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='El Campo <b> Nombre </b> solo admite letras ', regex='^[A-Za-zñÑáéíóúÁÉÍÓÚ. ]+$')]),
        ),
        migrations.AlterField(
            model_name='categoriausuario',
            name='nombre',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>Nombre</b> debe tener máximo 50 caracteres'}, max_length=50, validators=[django.core.validators.RegexValidator(message='El Campo <b> Nombre </b> solo admite letras ', regex='^[A-Za-zñÑáéíóúÁÉÍÓÚ. ]+$')]),
        ),
        migrations.AlterField(
            model_name='especialidadcongreso',
            name='nombre',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>Nombre</b> debe tener máximo 50 caracteres'}, max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='El Campo <b> Nombre </b> solo admite letras ', regex='^[A-Za-zñÑáéíóúÁÉÍÓÚ. ]+$')]),
        ),
        migrations.AlterField(
            model_name='especialidades',
            name='nombre',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>Nombre</b> debe tener máximo 50 caracteres'}, max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='El Campo <b> Nombre </b> solo admite letras ', regex='^[A-Za-zñÑáéíóúÁÉÍÓÚ. ]+$')]),
        ),
        migrations.AlterField(
            model_name='genero',
            name='denominacion',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>Denominación</b> debe tener máximo 20 caracteres'}, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='El Campo <b> Género </b> solo admite letras ', regex='^[A-Za-zñÑáéíóúÁÉÍÓÚ. ]+$')]),
        ),
        migrations.AlterField(
            model_name='pais',
            name='denominacion',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>Denominación</b> debe tener máximo 50 caracteres'}, max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='El Campo <b> País </b> solo admite letras ', regex='^[A-Za-zñÑáéíóúÁÉÍÓÚ. ]+$')]),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='num_telefono',
            field=models.CharField(max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Entre un No. de <b>Teléfono</b> correcto. Ej. <b>(+99)999-999-999</b>', regex='^[0-9()+-]+$')]),
        ),
        migrations.AlterField(
            model_name='sociocongreso',
            name='url',
            field=models.URLField(error_messages={'max_length': 'El Campo <b>URL</b> debe tener máximo 250 caracteres'}, max_length=250),
        ),
        migrations.CreateModel(
            name='TrabajosInvestigacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='MedCongressApp/static/'), upload_to='trabajos')),
                ('descripcion', models.TextField()),
                ('autor', models.CharField(error_messages={'max_length': 'El Campo <b>Denominación</b> debe tener máximo 50 caracteres'}, max_length=50, validators=[django.core.validators.RegexValidator(message='El Campo <b> País </b> solo admite letras ', regex='^[A-Za-zñÑáéíóúÁÉÍÓÚ. ]+$')])),
                ('cod_video', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='MedCongressApp/static/'), upload_to='usuarios')),
                ('congreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedCongressApp.Congreso')),
            ],
            options={
                'verbose_name': 'TrabajosInvestigacion',
            },
        ),
    ]
