# Generated by Django 2.2.3 on 2021-03-04 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0098_trabajosinvestigacion_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajosinvestigacion',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
