# Generated by Django 2.2.3 on 2021-03-08 22:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0099_auto_20210304_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajosinvestigacion',
            name='path',
            field=models.CharField(help_text='campo para identificarlo por la URL', max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='trabajosinvestigacion',
            name='autor',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>Autor</b> debe tener máximo 50 caracteres'}, max_length=50, validators=[django.core.validators.RegexValidator(message='El Campo <b> Autor </b> solo admite letras ', regex='^[A-Za-zñÑáéíóúÁÉÍÓÚ., ]+$')]),
        ),
        migrations.AlterField(
            model_name='trabajosinvestigacion',
            name='titulo',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>Título</b> debe tener máximo 250 caracteres'}, max_length=250, unique=True),
        ),
    ]
