# Generated by Django 2.2.3 on 2021-04-08 14:44

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0100_auto_20210308_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='congreso',
            name='imagen_home',
            field=models.ImageField(blank=True, error_messages={'blank': 'Debe  entrar una <b> Imagen Segundaria </b>'}, null=True, storage=django.core.files.storage.FileSystemStorage(location='MedCongressApp/static/'), upload_to='congreso'),
        ),
        migrations.AlterField(
            model_name='avalcongreso',
            name='nombre',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>Nombre</b> debe tener máximo 50 caracteres', 'unique': 'Ya existe un <b> Patrocinador</b> con este <b>Nombre</b>'}, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='congreso',
            name='foto_constancia',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='MedCongressApp/static/congreso/img_constancia'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='congreso',
            name='imagen_seg',
            field=models.ImageField(error_messages={'blank': 'Debe  entrar una <b> Imagen Segundaria </b>'}, storage=django.core.files.storage.FileSystemStorage(location='MedCongressApp/static/'), upload_to='congreso'),
        ),
        migrations.AlterField(
            model_name='ofrecemos',
            name='icono',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='MedCongressApp/static/'), upload_to='assets/img/iconos', verbose_name='icono'),
        ),
        migrations.AlterField(
            model_name='sociocongreso',
            name='nombre',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>Nombre</b> debe tener máximo 50 caracteres', 'unique': 'Ya existe un <b> Patrocinador</b> con este <b>Nombre</b>'}, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='trabajosinvestigacion',
            name='titulo',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>Título</b> debe tener máximo 250 caracteres', 'unique': 'Ya existe un <b> Trabajo de Investigación</b> con ese título'}, max_length=250, unique=True),
        ),
    ]
