# Generated by Django 2.2.3 on 2021-04-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0101_auto_20210408_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='congreso',
            name='is_home',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
