# Generated by Django 2.2.3 on 2021-05-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0103_auto_20210430_0831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sala',
            options={'verbose_name': 'Sala', 'verbose_name_plural': 'Salas'},
        ),
        migrations.AddField(
            model_name='sala',
            name='path',
            field=models.CharField(default=0, help_text='campo para identificarlo por la URL', max_length=250),
            preserve_default=False,
        ),
    ]
