# Generated by Django 2.2.3 on 2021-05-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0104_auto_20210501_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='published',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
