# Generated by Django 2.2.3 on 2021-05-11 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0105_sala_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('mensaje', models.CharField(max_length=250)),
                ('tipo', models.CharField(max_length=100)),
                ('congreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedCongressApp.Congreso')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedCongressApp.PerfilUsuario')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
    ]
