# Generated by Django 2.2.3 on 2021-05-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0106_useractivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivitylog',
            name='tiempo',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
