# Generated by Django 2.2.3 on 2021-05-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0107_useractivitylog_tiempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivitylog',
            name='fecha',
            field=models.DateTimeField(editable=False),
        ),
    ]
