# Generated by Django 2.2.3 on 2021-05-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0108_auto_20210512_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivitylog',
            name='tiempo',
            field=models.DateTimeField(editable=False),
        ),
    ]
