# Generated by Django 2.2.3 on 2021-05-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0110_auto_20210512_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivitylog',
            name='tiempo',
            field=models.CharField(max_length=100),
        ),
    ]
