# Generated by Django 2.2.3 on 2021-06-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0111_auto_20210512_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='color',
            field=models.CharField(default='#ffffff', max_length=10),
        ),
    ]
