# Generated by Django 2.2.3 on 2021-06-03 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0112_sala_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='color',
            field=models.CharField(default='#4A5966', max_length=10),
        ),
    ]
