# Generated by Django 2.2.3 on 2021-06-11 01:31

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0113_auto_20210602_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloque',
            name='cod_video',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloque',
            name='imagen',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='MedCongressApp/static/'), upload_to='bloque'),
        ),
        migrations.AlterField(
            model_name='congreso',
            name='published',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sala',
            name='published',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
