# Generated by Django 2.2.3 on 2021-06-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0114_auto_20210610_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='ponencia_streamming',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
