# Generated by Django 2.2.3 on 2021-06-22 14:20

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0115_sala_ponencia_streamming'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='imagen_home',
            field=models.ImageField(blank=True, error_messages={'blank': 'Debe  entrar una <b> Imagen Segundaria </b>'}, null=True, storage=django.core.files.storage.FileSystemStorage(location='MedCongressApp/static/'), upload_to='salas'),
        ),
        migrations.AddField(
            model_name='sala',
            name='imagen_seg',
            field=models.ImageField(blank=True, error_messages={'blank': 'Debe  entrar una <b> Imagen Segundaria </b>'}, null=True, storage=django.core.files.storage.FileSystemStorage(location='MedCongressApp/static/'), upload_to='salas'),
        ),
        migrations.AddField(
            model_name='sala',
            name='meta_description',
            field=models.TextField(blank=True, error_messages={'max_length': 'El Campo <b>Metas Principales Descripción</b> debe tener máximo 160 caracteres'}, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='sala',
            name='meta_keywords',
            field=models.TextField(blank=True, error_messages={'max_length': 'El Campo <b>Metas Principales Palabras Claves </b> debe tener máximo 250 caracteres'}, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='sala',
            name='meta_og_description',
            field=models.TextField(blank=True, error_messages={'max_length': 'El Campo <b>Metas para FaceBook Descripción</b> debe tener máximo 160 caracteres'}, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='sala',
            name='meta_og_imagen',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='MedCongressApp/static/'), upload_to='metas'),
        ),
        migrations.AddField(
            model_name='sala',
            name='meta_og_title',
            field=models.CharField(blank=True, error_messages={'max_length': 'El Campo <b>Metas para FaceBook Título</b> debe tener máximo 50 caracteres'}, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sala',
            name='meta_og_type',
            field=models.CharField(blank=True, error_messages={'max_length': 'El Campo <b>Metas para FaceBook Tipo</b> debe tener máximo 50 caracteres'}, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sala',
            name='meta_og_url',
            field=models.CharField(blank=True, error_messages={'max_length': 'El Campo <b>Metas para FaceBook URL</b> debe tener máximo 250 caracteres'}, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='sala',
            name='meta_title',
            field=models.CharField(blank=True, error_messages={'max_length': 'El Campo <b>Metas Principales Título </b> debe tener máximo 50 caracteres'}, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sala',
            name='meta_twitter_card',
            field=models.CharField(blank=True, error_messages={'max_length': 'El Campo <b>Metas para Redes Sociales Card</b> debe tener máximo 50 caracteres'}, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sala',
            name='meta_twitter_creator',
            field=models.CharField(blank=True, error_messages={'max_length': 'El Campo <b>Metas para Redes Sociales Creador</b> debe tener máximo 50 caracteres'}, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sala',
            name='meta_twitter_site',
            field=models.CharField(blank=True, error_messages={'max_length': 'El Campo <b>Metas para Redes Sociales Sitio</b> debe tener máximo 250 caracteres'}, max_length=250, null=True),
        ),
    ]
