# Generated by Django 2.2.3 on 2021-07-05 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0116_auto_20210622_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='imagen_home',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='imagen_seg',
        ),
    ]
