# Generated by Django 2.2.3 on 2021-07-15 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0117_auto_20210705_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='relcongresouser',
            name='is_beca',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='categoriapagocongreso',
            name='nombre',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>Nombre</b> debe tener máximo 50 caracteres'}, max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='El Campo <b> Nombre </b> solo admite letras ', regex='^[A-Za-zñÑáéíóúÁÉÍÓÚ.,+-*= ]+$')]),
        ),
        migrations.AlterField(
            model_name='categoriausuario',
            name='nombre',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>Nombre</b> debe tener máximo 50 caracteres'}, max_length=50, validators=[django.core.validators.RegexValidator(message='El Campo <b> Nombre </b> solo admite letras ', regex='^[A-Za-zñÑáéíóúÁÉÍÓÚ.,+-*= ]+$')]),
        ),
        migrations.AlterField(
            model_name='especialidadcongreso',
            name='nombre',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>Nombre</b> debe tener máximo 50 caracteres'}, max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='El Campo <b> Nombre </b> solo admite letras ', regex='^[A-Za-zñÑáéíóúÁÉÍÓÚ.,+-*= ]+$')]),
        ),
        migrations.AlterField(
            model_name='especialidades',
            name='nombre',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>Nombre</b> debe tener máximo 50 caracteres'}, max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='El Campo <b> Nombre </b> solo admite letras ', regex='^[A-Za-zñÑáéíóúÁÉÍÓÚ.,+-*= ]+$')]),
        ),
        migrations.AlterField(
            model_name='genero',
            name='denominacion',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>Denominación</b> debe tener máximo 20 caracteres'}, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='El Campo <b> Género </b> solo admite letras ', regex='^[A-Za-zñÑáéíóúÁÉÍÓÚ.,+-*= ]+$')]),
        ),
        migrations.AlterField(
            model_name='pais',
            name='denominacion',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>Denominación</b> debe tener máximo 50 caracteres'}, max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='El Campo <b> País </b> solo admite letras ', regex='^[A-Za-zñÑáéíóúÁÉÍÓÚ.,+-*= ]+$')]),
        ),
        migrations.AlterField(
            model_name='trabajosinvestigacion',
            name='autor',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>Autor</b> debe tener máximo 50 caracteres'}, max_length=50, validators=[django.core.validators.RegexValidator(message='El Campo <b> Autor </b> solo admite letras ', regex='^[A-Za-zñÑáéíóúÁÉÍÓÚ.,+-*= ]+$')]),
        ),
    ]
