# Generated by Django 2.2.3 on 2021-07-16 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0118_auto_20210715_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='BecasPendientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('congreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedCongressApp.Congreso')),
            ],
            options={
                'verbose_name': 'BecasPendientes',
            },
        ),
    ]
