# Generated by Django 2.2.3 on 2021-07-16 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0119_becaspendientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relcongresouser',
            name='categoria_pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MedCongressApp.CategoriaPagoCongreso'),
        ),
    ]
