# Generated by Django 2.2.3 on 2021-08-02 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0120_auto_20210716_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='orden',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='categoriapagocongreso',
            name='nombre',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>Nombre</b> debe tener máximo 50 caracteres'}, max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='El Campo <b> Nombre </b> solo admite números, letras y (.,+-)', regex='^[\\w.,+\\- ]+$')]),
        ),
        migrations.AlterField(
            model_name='categoriausuario',
            name='nombre',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>Nombre</b> debe tener máximo 50 caracteres'}, max_length=50, validators=[django.core.validators.RegexValidator(message='El Campo <b> Nombre </b> solo admite números, letras y (.,+-)', regex='^[\\w.,+\\- ]+$')]),
        ),
        migrations.AlterField(
            model_name='especialidadcongreso',
            name='nombre',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>Nombre</b> debe tener máximo 50 caracteres'}, max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='El Campo <b> Nombre </b> solo admite números, letras y (.,+-)', regex='^[\\w.,+\\- ]+$')]),
        ),
        migrations.AlterField(
            model_name='especialidades',
            name='nombre',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>Nombre</b> debe tener máximo 50 caracteres'}, max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='El Campo <b> Nombre </b> solo admite números, letras y (.,+-)', regex='^[\\w.,+\\- ]+$')]),
        ),
        migrations.AlterField(
            model_name='genero',
            name='denominacion',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>Denominación</b> debe tener máximo 20 caracteres'}, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='El Campo <b> Género </b> solo admite números, letras y (.,+-)', regex='^[\\w.,+\\- ]+$')]),
        ),
        migrations.AlterField(
            model_name='pais',
            name='denominacion',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>Denominación</b> debe tener máximo 50 caracteres'}, max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='El Campo <b> País </b> solo admite números, letras y (.,+-)', regex='^[\\w.,+\\- ]+$')]),
        ),
        migrations.AlterField(
            model_name='trabajosinvestigacion',
            name='autor',
            field=models.CharField(error_messages={'max_length': 'El Campo <b>Autor</b> debe tener máximo 50 caracteres'}, max_length=50, validators=[django.core.validators.RegexValidator(message='El Campo <b> Autor </b> solo admite números, letras y (.,+-)', regex='^[\\w.,+\\- ]+$')]),
        ),
    ]
