# Generated by Django 2.2.3 on 2021-08-25 16:05

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0121_auto_20210802_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='congreso',
            name='foto_const_moderador',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='MedCongressApp/static/congreso/img_constancia'), upload_to=''),
        ),
        migrations.AddField(
            model_name='congreso',
            name='foto_const_ponente',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='MedCongressApp/static/congreso/img_constancia'), upload_to=''),
        ),
    ]
