# Generated by Django 2.2.3 on 2022-02-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCongressApp', '0125_organizador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relcongresouser',
            name='is_constancia',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
